### ISSUE TITLE
libuv installed other than /usr?

### ISSUE THREAD

**Issue by RSully** [CaramelForSwift/CUv#1]
It looks like the modulemap specifies `/usr/include/uv.h` but as a non-root user I compiled libuv into my $HOME. Is this configurable?

**Comment by stevestreza** [comment]
As of right now, no. Per the [Swift package manager documentation](https://github.com/apple/swift-package-manager/blob/master/Documentation/SystemModules.md#cross-platform-module-maps):

> Module maps must contain absolute paths, thus they are not cross-platform. We intend to provide a solution for this in the package manager.

In the short term you can fork, change the module map path, tag, push, and use your own repo in the Package.swift file.

**Comment by RSully** [comment]
Alright, I'll just use a VM for now. Thanks!
